// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserDropdownController from "./user_dropdown_controller"
application.register("user-dropdown", UserDropdownController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import MarketSectorController from "./market_sector_controller"
application.register("market-sector", MarketSectorController)

import PyramidController from "./pyramid_controller"
application.register("pyramid", PyramidController)

import LoginTabsController from "./login_tabs_controller"
application.register("login-tabs", LoginTabsController)

import QrcodeController from "./qrcode_controller"
application.register("qrcode", QrcodeController)
